env : "local" # local, dev, prod

http_server:
  address: "localhost:8082"
  timeout: 4s
  iddle_timeout: 60s

postgres:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "postgres"
  dbname: "urlDB"
# 